### ISSUE TITLE
Constructors of mpmpc_queue

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#114]
Constructors of `mpmc_queue` need review:

1. Use initialization sequence before entering the body.
1. Make sure that members are initialized in the correct order.
1. Make sure that all members are initialized.
1. Factor out common initialization to non-static-data-member-initializer.
1. Use delegating constructors for simplicity.

**Comment by jdgarciauc3m** [comment]
Additionally:

1. Leave a single constructor with the second argument defaulted.
1. Change the second argument of the constructor to an enum class with values `lockfree` and `blocking`.

**Comment by Drioastorga** [comment]
The mpmc_queue has been reviewed and modified acordingly.

Changes:
- A file with the enum class Queue_modes has been introduced.
- Instead of using a boolean, the queue mode is defined by the aforementioned enum class.
- The constructor with a single parameter has been deleted. 
- Now there is only one constructor with a default value for the second parameter.
- The data members initializations are performed in the initialization list of the constructor.
- The data member that defines the queue mode in the execution models has been modified from bolean type to Queue_mode.

**Comment by jdgarciauc3m** [comment]
Solved by PR #143
