### ISSUE TITLE
Study and support heterogeneous reductions

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#342]
Study and support heterogeneous reductions for specific cases

This will imply:
1. The applications programmer has to provide 2 different combiner operations:
  a. The heterogeneous sequential combiner.
  b. The homogeneous parallel-friendly combiner.
2. The identity value cannot be omitted.

This partially solved #290

**Comment by mdrocco** [comment]
A common syntax for this is the `parallel_reduce ` in TBB:
https://software.intel.com/en-us/node/506154

The semantics is usually defined only if the identity value is passed as parameter (non-deterministic otherwise). I formalized it in a technical report (p. 17, fold+reduce):
https://arxiv.org/pdf/1705.01629.pdf

This is not a trivial object, but it is a well-established way to support heterogeneous reduction in parallel execution environments.

**Comment by jdgarciauc3m** [comment]
After further discussion we think that heterogeneous reductions can be better expressed as a `map_reduce`.

Therefore GrPPI does not support heterogeneous reductions.
