### ISSUE TITLE
Function arguments by forwarding reference

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#59]
Revise all patterns to take functors as forwarding references.

As an example:

~~~c++
template <typename InputIt, typename OutputIt, typename TaskFunc>
void map(parallel_execution_omp p, InputIt first, InputIt last, OutputIt firstOut, TaskFunc const &taskf)
~~~

should be transformed into

~~~c++
template <typename InputIt, typename OutputIt, typename TaskFunc>
void map(parallel_execution_omp p, InputIt first, InputIt last, OutputIt firstOut, TaskFunc && taskf)
~~~

**Comment by AndresSanchezCuadrado** [comment]
I have used sed to make the changes. I only had to change the templates for composed_pipeline in pipeline_seq.h and pipeline_thr.h files to avoid errors.

Everything seems to work properly, because the tests are compiled and run properly.

However, the amount of elements changed is quite big.

Is there a proper way to make sure everything is correct? Is working, but maybe something has been changed to const & to && and it shouldnt.

**Comment by jdgarciauc3m** [comment]
That is the purpose of code reviews. Please, do a pull request.

**Comment by jdgarciauc3m** [comment]
This is pull request #73

**Comment by jdgarciauc3m** [comment]
Solved
