### ISSUE TITLE
Add clang-tidy to unit-tests

### ISSUE THREAD

**Issue by jdgarciauc3m** [arcosuc3m/grppi#67]
Define an appropriate configuration file for clang-tidy and integrate clan-tidy checks in unit-tests

**Comment by jdgarciauc3m** [comment]
This is only supported only under CMake 3.6 and upper.

We need to use:

set_property(
    TARGET farm1
    PROPERTY CXX_CLANG_TIDY "clang-tidy;-checks=*")

**Comment by tete17** [comment]
I have been experimenting with this a bit and i found a few that may be worth mentioning:

1. Having this always enabled on the unitary test, may not be as good idea. The build times are more than significantly longer. Im seeing times of 15 minutes with 4 parallel jobs in a 4 core processor, where previously with the same cpu i was getting 1,5 minutes. I think it is possible to add clang-tidy as a custom target to be run separately instead of every time we need to run the unit tests (Maybe this was the original idea and i understood it wrongly, Please let me know).

2. I dont know how much value this can add to the unitary tests. I think we would benefit more from this process if it would be applied to the examples since those can actually be used by other people in production code, instead of unitary tests. Furthermore all macro expansion that google test really muds the warning messages

3. it is hard to identify the exact version of clang-tidy to be used as oppose to the compiler version. According to this web page (http://www.mariobadr.com/using-clang-tidy-with-cmake-36.html) we can exactly specify the clang-tidy version to be required bu using "clang-tidy-5.0" for example, or depend on the one installed by using "clang-tidy" i dont see an obvious way to enforce a version greater or equal to some baseline, but this could be due to my inexperties in cmake scripting.

**Comment by jdgarciauc3m** [comment]
1.- Yes adding a custom target seems the right thing to do for now.

2.- clang-tidy on the unit tests adds value. The reason is that unit tests should have high coverage of the library and will be used to discover weaknesses in the library implementation itself, because this is a header only library.

3. Let's require clang-tidy-5 for now.

**Comment by jdgarciauc3m** [comment]
After analyzing results I think we need to postpone this issue until we find a way to exclude messages from analyizing third party libraries. In particular, there are a number of diagnostics generated from **Google Test** and **Intel TBB**.

**Comment by jdgarciauc3m** [comment]
We are going to close this one. It does not seem practical for unit tests.
